project: OnlinePaymentsKit.xcodeproj
schemes:
- OnlinePaymentsKit
targets:
- OnlinePaymentsKit
- OnlinePaymentsKitTests
clean_build: true
retain_public: true
build_arguments:
- -destination
- platform="iOS Simulator,name=iPhone 15,OS=17.0"
